version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306    
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db                       

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: wordpress   
      MYSQL_USER: root   
      MYSQL_PASSWORD: root        
    volumes:
      - db_data:/var/lib/mysql    

volumes:
  db_data:                        
