version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306    
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: wordpress   
      # Removed MYSQL_USER and MYSQL_PASSWORD for the root user
    volumes:
      - db_data:/var/lib/mysql
    restart: always  # Optional: restarts the db container if it stops unexpectedly

volumes:
  db_data:
    driver: local
